import {Component, Input, OnDestroy, OnInit, Renderer2} from '@angular/core';
import {ActivatedRoute, NavigationEnd, Router} from '@angular/router';
import {select, Store} from '@ngrx/store';
import {UpdateCategory} from '../../../core/store/ui/ui.actions';

@Component({
  selector: 'emitter-search-navigator',
  templateUrl: './search-navigator.component.html',
  styleUrls: ['./search-navigator.component.scss']
})

export class SearchNavigatorComponent implements OnInit, OnDestroy {
  // @Input('categoryList') categoryList;
  // @Input('result') result;
  objectKeys = Object.keys;


  result;
  storeSubscription$;
  categoryList;
  previous;
  currentSlug;


  imageIndex = 0;

  itemListArray;

  ///////////////////////
  totalCount;
  totalPage;
  totalPageArray;
  maxRow = 18;
  currentList;
  currentPage = 1;

  constructor(
    private renderer: Renderer2,
    private store: Store<any>,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.storeSubscription$ = this.store.pipe(select('ui')).subscribe( val => {
      this.categoryList = val.currentCategoryList.entities;
      this.result = val.currentCategoryList.result;
      this.previous = val.currentCategoryList.previous;
      this.currentSlug = val.currentCategoryList.currentSlug;
      console.log(this.result);
      // console.log(val);
      // console.log(this.categoryList);
      // console.log(this.result);
    });
    const url = this.router.url.split('/');
  }

  ngOnDestroy() {
    console.log('destroyed navigator')
    this.storeSubscription$.unsubscribe();
  }

  ngOnInit() {
    this.totalCount = this.infoList.length;
    this.totalPage = this.totalCount / this.maxRow;
    this.totalPageArray =  Array(parseInt(this.totalPage, 10));
    this.totalPageArray.push(this.totalPageArray.length + 1);

    this.currentList = this.infoList.slice( 0, this.maxRow);
  }

  paginate(pageIndex) {
    this.currentPage = pageIndex;
    this.currentList = this.infoList.slice(  (this.currentPage - 1 ) * this.maxRow , this.currentPage * this.maxRow )
  }

  numberArray(n: number): any[] {
    return Array(n);
  }

  updateSecondCategory(index, slug) {
    const url = this.router.url.split('/')
    if (url[url.length - 1] === slug) { return; };


    this.store.dispatch(new UpdateCategory({ secondSortKey : slug }));
    this.router.navigate( ['/shops/c/pantry-and-household/' + slug], {relativeTo : this.route});
  }

  updateThirdCategory(index, secondSlug, thirdSlug) {
    const url = this.router.url.split('/')
    console.log(url.length);
    // if (url[url.length - 1] === slug) { return; };

    this.store.dispatch(new UpdateCategory({ secondSortKey : secondSlug, thirdSortKey: thirdSlug }));
    // this.store.dispatch(new UpdateThirdCategory({secondSortBy : index}));
    this.router.navigate( ['/shops/c/pantry-and-household/' + secondSlug + '/' + thirdSlug], {relativeTo : this.route});
  }

  onedepthFold( dom, label ) {
    if ( dom.style.maxHeight === '3500px' ) {

      this.renderer.setStyle(label , 'transform', 'rotate(0deg)');
      this.renderer.setStyle(dom, 'opacity', '0');
      this.renderer.setStyle(dom, 'max-height', '0px');

    } else {

      this.renderer.setStyle(label , 'transform', 'rotate(-180deg)');
      this.renderer.setStyle(dom, 'opacity', '1');
      this.renderer.setStyle(dom, 'max-height', '3500px');
    }
  }

  twodepthFold( dom, label ) {
    if ( dom.style.maxHeight === '700px' ) {
      this.renderer.setStyle(label , 'transform', 'rotate(0deg)');
      this.renderer.setStyle(dom, 'opacity', '0');
      this.renderer.setStyle(dom, 'max-height', '0px');

    } else {
      this.renderer.setStyle(label , 'transform', 'rotate(-180deg)');
      this.renderer.setStyle(dom, 'opacity', '1');
      this.renderer.setStyle(dom, 'max-height', '700px');

    }
  }

  nonCompareFunction( a, b ) {
    return 0;
  }





  infoList = [
    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },
    {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 5,
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    },   {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg'
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    },
    {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 30,
      discountPercent: 25,
      currentPrice: 10,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg'
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    },   {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 30,
      discountPercent: 25,
      currentPrice: 10,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg'
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    },   {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 30,
      discountPercent: 25,
      currentPrice: 10,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg'
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    },   {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 30,
      discountPercent: 25,
      currentPrice: 10,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg'
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    },   {
      brand: 'Endangered Species Chocolate',
      productName: 'ONE Protein Bar, Birthday Cake, 2.12 oz. (12 Pack), Gluten-Free Protein Bar with High Protein (20g) and Low Sugar (1g), Guilt Free…',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 30,
      discountPercent: 25,
      currentPrice: 10,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg'
    },
    {
      brand: 'Rxbar',
      productName: 'RXBAR Whole Food Protein Bar, Chocolate Sea Salt, 1.83 Ounce (Pack of 12)',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg'
    },
    {
      brand: 'Shanti Bar',
      productName: 'Shanti Stainless Steel Flat Speed Bar Bottle Openet',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 50,
      discountPercent: 50,
      currentPrice: 25,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg'
    } ,   {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },    {
      brand: '라라바',
      productName: '라라바 글루텐프리 레몬 바 1.6oz 5개입 박스',
      rating: 4.4,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-2.jpg',
      deliveryPoint : 1,
    } , {
      brand: '오예',
      productName: '오예바 원 바 벌쓰데이 케이크 프로틴바 12개',
      rating: 3.9,
      reviewCount: 99,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-5.jpg',
      deliveryPoint : 2,
    },
    {
      brand: '알엑스바',
      productName: '알엑스바 리얼 푸드 프로틴 에너지바 믹스드 베리 52G / 1.83OZ',
      rating: 1.5,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-3.jpg',
      deliveryPoint : 3,
    },
    {
      brand: '샨티바',
      productName: '샨티바 리얼 푸드 프로틴 에너지바 코코넛 52G/ 1.83OZ',
      rating: 2.3,
      reviewCount: 15,
      msrpDiscountPrice: 57200,
      discountPercent: 50,
      currentPrice: 28600,
      imgSrc: 'http://img.onpicks.com/p-similar-4.jpg',
      deliveryPoint : 4,
    },
  ];

}
